steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image-from-dockerfile'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image-to-gcr'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args: 
      - 'beta'
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast2'
substitutions:
  _REGION: asia-northeast2
  _SERVICE_NAME: iine